/**
 * Initialise mockforme on top of the page
 */
import { mockforme as mockformeServer } from "mockforme/server";

import { InitMockForMeClient } from "@/app/components/mockformeClient";

if (process.env.NODE_ENV === "development") {
  const TOKEN = process.env.NEXT_PUBLIC_MFM_API_TOKEN;
  
  if (TOKEN) {
    try {
      mockformeServer(TOKEN).run((apiMappings) => {
        console.log("<mockforme apiMappings>", apiMappings);
      }, (err) => {
        console.log("<mockforme error>", err);
      });
    } catch (err) {
      console.log("Error in mockforme server initialisation", err);
    }
  }
}

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <InitMockForMeClient />
        {children}
      </body>
    </html>
  );
}
